added styles gulp task-dz-05
Irina-Alieva/dz-gulp-1 pull request #1
Opened 2018-02-04 18:27 UTC by Irina-Alieva

2018-02-04 20:37 UTC, nobleworkshop requested changes
Проверил, есть необходимые изменения. Надо доработать.

2018-02-04 20:37 UTC, nobleworkshop commented on gulpfile.js
> +gulp.task('styles', ['less'], function() {
Вы переименовали задачу для сервера в style, ее надо было оставить server

2018-02-04 20:37 UTC, nobleworkshop commented on gulpfile.js
>  gulp.task('less', function() {
А less надо переименовать в styles

2018-02-04 20:37 UTC, nobleworkshop commented on gulpfile.js
> +    gulp.watch('./app/less/**/*.less', ['less']);
и здесь в конце вызывать ['styles']

2018-02-04 20:37 UTC, nobleworkshop commented
@Irina-Alieva Проверил, есть необходимые изменения. Надо доработать.

2018-02-05 00:10 UTC, Irina-Alieva commented
@nobleworkshop  Правки внесла. Хотя и до правок работало. Я проверяла)

2018-02-05 13:17 UTC, nobleworkshop approved these changes
Looks good!)

2018-02-05 13:54 UTC, merged